/*

Quicksand 1.4

Reorder and filter items with a nice shuffling animation.

Copyright (c) 2010 Jacek Galanciak (razorjack.net) and agilope.com
Big thanks for Piotr Petrus (riddle.pl) for deep code review and wonderful docs & demos.

Dual licensed under the MIT and GPL version 2 licenses.
http://github.com/jquery/jquery/blob/master/MIT-LICENSE.txt
http://github.com/jquery/jquery/blob/master/GPL-LICENSE.txt

Project site: http://razorjack.net/quicksand
Github site: http://github.com/razorjack/quicksand

*/

(function(b){var u=function(b){var m=b.clone(),l=b.find("canvas");l.length&&m.find("canvas").each(function(a){this.getContext("2d").drawImage(l.get(a),0,0)});return m};b.fn.quicksand=function(y,m,l){var a={duration:750,easing:"swing",attribute:"data-id",adjustHeight:"auto",adjustWidth:"auto",useScaling:!1,enhancement:function(a){},selector:"> *",atomic:!1,dx:0,dy:0,maxWidth:0,retainExisting:!0},D=function(){for(var a=["transform","WebkitTransform","MozTransform","OTransform","msTransform"],b=document.createElement("div"),
h=0;h<a.length;h++)if("undefined"!=typeof b.style[a[h]])return!0;return!1}();b.extend(a,m);D&&"undefined"!=typeof b.fn.scale||(a.useScaling=!1);var r;"function"==typeof m?r=m:typeof("function"==l)&&(r=l);return this.each(function(c){var m,h=[],n;n="function"==typeof a.attribute?b(y):u(b(y).filter("["+a.attribute+"]"));var g=b(this);c=b(this).css("height");var l=b(this).css("width"),s,z=!1,A=!1,p=b(g).offset(),t=[],q=b(this).find(a.selector),B=b(q).innerWidth();if(navigator.userAgent.match(/msie [6]/i))g.html("").append(n);
else{var C=0,v=function(){b(this).css("margin","").css("position","").css("top","").css("left","").css("opacity","");if(!C){C=1;if(!a.atomic){var d=g.find(a.selector);if(a.retainExisting){var f=b([]);k.find(a.selector).each(function(e){var c=b([]);if("function"==typeof a.attribute){var h=a.attribute(b(this));d.each(function(){if(a.attribute(this)==h)return c=b(this),!1})}else c=d.filter("["+a.attribute+'="'+b(this).attr(a.attribute)+'"]');0<c.length&&(f=f.add(c),0===e?g.prepend(c):c.insertAfter(g.find(a.selector).get(e-
1)))});d.not(f).remove()}else g.prepend(k.find(a.selector)),d.remove();z&&g.css("height",s);A&&g.css("width",l)}a.enhancement(g);"function"==typeof r&&r.call(this)}!1===a.adjustHeight&&g.css("height","auto");!1===a.adjustWidth&&g.css("width","auto")},e=g.offsetParent(),d=e.offset();"relative"==e.css("position")?"body"!=e.get(0).nodeName.toLowerCase()&&(d.top+=parseFloat(e.css("border-top-width"))||0,d.left+=parseFloat(e.css("border-left-width"))||0):(d.top-=parseFloat(e.css("border-top-width"))||
0,d.left-=parseFloat(e.css("border-left-width"))||0,d.top-=parseFloat(e.css("margin-top"))||0,d.left-=parseFloat(e.css("margin-left"))||0);isNaN(d.left)&&(d.left=0);isNaN(d.top)&&(d.top=0);d.left-=a.dx;d.top-=a.dy;g.css("height",b(this).height());g.css("width",b(this).width());q.each(function(a){t[a]=b(this).offset()});b(this).stop();var w=0,x=0;q.each(function(c){b(this).stop();var f=b(this).get(0);"absolute"==f.style.position?(w=-a.dx,x=-a.dy):(w=a.dx,x=a.dy);f.style.position="absolute";f.style.margin=
"0";a.adjustWidth||(f.style.width=B+"px");f.style.top=t[c].top-parseFloat(f.style.marginTop)-d.top+x+"px";f.style.left=t[c].left-parseFloat(f.style.marginLeft)-d.left+w+"px";0<a.maxWidth&&t[c].left>a.maxWidth&&(f.style.display="none")});var k=u(b(g)),e=k.get(0);e.innerHTML="";e.setAttribute("id","");e.style.height="auto";e.style.width=g.width()+"px";k.append(n);k.insertBefore(g);k.css("opacity",0);e.style.zIndex=-1;e.style.margin="0";e.style.position="absolute";e.style.top=p.top-d.top+"px";e.style.left=
p.left-d.left+"px";"dynamic"===a.adjustHeight?g.animate({height:k.height()},a.duration,a.easing):"auto"===a.adjustHeight&&(s=k.height(),parseFloat(c)<parseFloat(s)?g.css("height",s):z=!0);"dynamic"===a.adjustWidth?g.animate({width:k.width()},a.duration,a.easing):"auto"===a.adjustWidth&&(c=k.width(),parseFloat(l)<parseFloat(c)?g.css("width",c):A=!0);q.each(function(c){var f=[];"function"==typeof a.attribute?(m=a.attribute(b(this)),n.each(function(){if(a.attribute(this)==m)return f=b(this),!1})):f=
n.filter("["+a.attribute+'="'+b(this).attr(a.attribute)+'"]');f.length?a.useScaling?h.push({element:b(this),dest:f,style:{top:b(this).offset().top,left:b(this).offset().left,opacity:""},animation:{top:f.offset().top-d.top,left:f.offset().left-d.left,opacity:1,scale:"1.0"}}):h.push({element:b(this),dest:f,style:{top:b(this).offset().top,left:b(this).offset().left,opacity:""},animation:{top:f.offset().top-d.top,left:f.offset().left-d.left,opacity:1}}):a.useScaling?h.push({element:b(this),animation:{opacity:"0.0",
style:{top:b(this).offset().top,left:b(this).offset().left,opacity:""},scale:"0.0"}}):h.push({element:b(this),style:{top:b(this).offset().top,left:b(this).offset().left,opacity:""},animation:{opacity:"0.0"}})});n.each(function(c){var f=[],e=[];"function"==typeof a.attribute?(m=a.attribute(b(this)),q.each(function(){if(a.attribute(this)==m)return f=b(this),!1}),n.each(function(){if(a.attribute(this)==m)return e=b(this),!1})):(f=q.filter("["+a.attribute+'="'+b(this).attr(a.attribute)+'"]'),e=n.filter("["+
a.attribute+'="'+b(this).attr(a.attribute)+'"]'));if(0===f.length&&0<e.length){c=a.useScaling?{opacity:"1.0",scale:"1.0"}:{opacity:"1.0"};var k=u(e),l=k.get(0);l.style.position="absolute";l.style.margin="0";a.adjustWidth||(l.style.width=B+"px");l.style.top=e.offset().top-d.top+"px";l.style.left=e.offset().left-d.left+"px";k.css("opacity",0);a.useScaling&&k.scale(0);k.appendTo(g);(0===a.maxWidth||e.offset().left<a.maxWidth)&&h.push({element:b(k),dest:e,animation:c})}});k.remove();if(a.atomic){$toDelete=
g.find(a.selector);g.prepend(k.find(a.selector));for(c=0;c<h.length;c++)h[c].dest&&h[c].style?(p=h[c].dest,e=p.offset(),p.css({position:"relative",top:h[c].style.top-e.top,left:h[c].style.left-e.left}),p.animate({top:"0",left:"0"},a.duration,a.easing,v)):h[c].element.animate(h[c].animation,a.duration,a.easing,v);$toDelete.remove()}else for(a.enhancement(g),c=0;c<h.length;c++)h[c].element.animate(h[c].animation,a.duration,a.easing,v)}})}})(jQuery);